### ISSUE TITLE
Typo in namespace declaration

### ISSUE THREAD

**Issue by kkrebs** [gbv/digital-edition-archive#1]
this seems to be a c&p error, is MEI in namespace declaration instead of TEI

https://github.com/gbv/digital-edition-archive/blob/133640ebdf3d1e654453afd135658edfcd83c66c/digital-edition-archive-module/src/main/datamodel/def/tei.xml#L6

**Comment by sebhofmann** [comment]
Fixed by https://github.com/gbv/digital-edition-archive/commit/56bf7b6ea69e735f159d7fb9be14d17a9dd61e55
